version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - auth
    env_file:
      - .env

  db:
    image: postgres:15
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  auth:
    image: uchp/pocketbase
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - pbdata:/pb_data

volumes:
  pgdata:
  pbdata:
